versions = [{
		name : '1.0',
		desc : 'Initialisation des données du jeu.',
		chapters : [
			{ code:'EMP', name:'Empire', des:'Empire millénaire, gardien de l\'ordre établi et des traditions.' },
			{ code:'REB', name:'Rebellion', des:'Frondeurs et idéalistes, ils se sont rassemblés pour gagner leur Liberté.' },
			{ code:'CAR', name:'Cartels', des:'Opportunistes ou simples brigands, ils vivent en marge de la société et profitent de chaque occasion pour augmenter leurs richesses.' }
		],
		teams : [
			{ code:'TES', name:'Test', chapter:'EMP', des:'TODO.' },
			{ code:'HUT', name:'Hutt', chapter:'REB', des:'TODO.' },
			{ code:'VAG', name:'Vagans', chapter:'CAR', des:'TODO.' }
		],
		domains : [
			{ code:'LUM', name:'Lumière', des:'Domaine de l\'ordre, de la justice et de la pureté.' },
			{ code:'TEN', name:'Ténèbres', des:'Domaine du mal, de la peur et de la mort.' },
			{ code:'CHA', name:'Chaos', des:'Domaine de la guerre, de la destruction et de la colère.' },
			{ code:'NAT', name:'Nature', des:'Domaine de la vie, de la nature et de la croissance.' },
			{ code:'ESP', name:'Esprit', des:'Domaine de la connaissance, de l\'illusion et de la précision.' }
		],
		classes : [
			{ code:'ANG', name:'Ange', des:'Guerrier céleste.', attr:['FOR'], domain:'LUM', superClasse:null },
			{ code:'HOR', name:'Horreur', des:'Votre plus grand cauchemar.', attr:['RAP'], domain:'TEN', superClasse:null },
			{ code:'DEM', name:'Démon', des:'Prince de la destruction.', attr:['RES'], domain:'CHA', superClasse:null },
			{ code:'ERM', name:'Ermite', des:'Méfiez-vous de son air paisible.', attr:['DEX'], domain:'NAT', superClasse:null },
			{ code:'ASS', name:'Assassin', des:'Ne croisez pas son chemin.', attr:['PER'], domain:'ESP', superClasse:null },
			{ code:'MOI', name:'Moine', des:'Ardent défenseur de la foi.', attr:['RES', 'MEN'], domain:'LUM', superClasse:'ANG' },
			{ code:'CHE', name:'Chevalier', des:'Protecteur des faibles et bras armé de la justice.', attr:['DEX', 'RES'], domain:'LUM', superClasse:'ANG' },
			{ code:'ENC', name:'Enchanteur', des:'Détenteur de savoirs anciens, et magicien émérite.', attr:['PER', 'MEN'], domain:'LUM', superClasse:'ANG' },
			{ code:'CHN', name:'Chevalier noir', des:'Protecteur des forts et bras armé de l\'injustice.', attr:['DEX', 'FOR'], domain:'TEN', superClasse:'HOR' },
			{ code:'LIC', name:'Liche', des:'Se nourrit des vivants.', attr:['PER', 'FOR'], domain:'TEN', superClasse:'HOR' },
			{ code:'SOM', name:'Sombremage', des:'Morts ! Levez-vous !', attr:['DEX', 'MEN'], domain:'TEN', superClasse:'HOR' },
			{ code:'ART', name:'Artificier', des:'BoOm !', attr:['PER', 'DEX'], domain:'CHA', superClasse:'DEM' },
			{ code:'BER', name:'Berserker', des:'Violent et incontrolable.', attr:['RAP', 'FOR'], domain:'CHA', superClasse:'DEM' },
			{ code:'PYR', name:'Pyromancien', des:'Maîtrise les arcanes du feu.', attr:['RAP', 'MEN'], domain:'CHA', superClasse:'DEM' },
			{ code:'RAN', name:'Ranger', des:'Bon pied bon oeil.', attr:['RAP', 'PER'], domain:'NAT', superClasse:'ERM' },
			{ code:'DRU', name:'Druide', des:'Gardien des savoirs ancestraux.', attr:['PER', 'RES'], domain:'NAT', superClasse:'ERM' },
			{ code:'PRO', name:'Protecteur', des:'Véritable force de la nature.', attr:['FOR', 'RES'], domain:'NAT', superClasse:'ERM' },
			{ code:'ELE', name:'Elementaire', des:'Imperturbable.', attr:['FOR', 'MEN'], domain:'ESP', superClasse:'ASS' },
			{ code:'DUE', name:'Duelliste', des:'Rapide et précis.', attr:['RAP', 'DEX'], domain:'ESP', superClasse:'ASS' },
			{ code:'MAG', name:'Mage', des:'La puissance de l\'esprit.', attr:['RAP', 'MEN'], domain:'ESP', superClasse:'ASS' }
		],
		perks : [
			{ code:'AGI', name:'Agile', desc:'Un peu plus rapide que la moyenne...', 						classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'ATT', name:'Attentif', desc:'Un peu plus attentif que la moyenne...', 					classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'SOU', name:'Souple', desc:'Un peu plus souple que la moyenne...', 						classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'TRA', name:'Trapu', desc:'Un peu plus fort que la moyenne...', 							classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'RES', name:'Résistant', desc:'Un peu plus résistant que la moyenne...', 				classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'VOL', name:'Volontaire', desc:'Un peu plus volontaire que la moyenne...', 				classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'CON', name:'Concentré', desc:'Un peu plus concentré que la moyenne...', 				classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'INQ', name:'Inquiétant', desc:'Un quelque chose de dérangeant...', 						classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'END', name:'Endurant', desc:'Sait prendre les coups.', 									classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'BRU', name:'Brutal', desc:'Il fait mal, et ça lui plait.', 								classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'NER', name:'Nerveux', desc:'Agité de tics, et très rapide.', 							classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'OBS', name:'Observateur', desc:'Il identifie les faiblesses de ses adversaires.', 		classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'HAB', name:'Habile', desc:'Sait manier tout type d\'arme.', 							classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'FOR', name:'Fort', desc:'Des muscles saillants.', 										classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'INE', name:'Inébranlable', desc:'Le faire chuter tient de la performance !', 			classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'DET', name:'Déterminé', desc:'Il ne s\'en laisse pas compter.', 						classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'FOC', name:'Focalisé', desc:'Se choisit un objectif, et s\'y tient !', 					classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'MEN', name:'Menaçant', desc:'Ses adversaires sont obligés de l\'avoir à l\'oeil !', 	classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'SUR', name:'Survivant', desc:'Une capacité à survivre étonnante !', 					classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'CRU', name:'Cruel', desc:'Aime faire souffrir.', 										classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'VEL', name:'Véloce', desc:'Difficile de le suivre.', 									classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'VIG', name:'Vigilant', desc:'Rien ne lui échappe !', 									classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'INF', name:'Infaillible', desc:'Ne rate jamais sa cible.', 								classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'PUI', name:'Puissant', desc:'Une force qui impose le respect.', 						classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'INV', name:'Invincible', desc:'Les coups semblent ne rien lui faire...', 				classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'OBN', name:'Obstiné', desc:'Une vraie force de caractère !', 							classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'MAN', name:'Maniaque', desc:'Semble ne rien savoir faire d\'autre que son objectif du moment.', classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'TER', name:'Terrifiant', desc:'Sa simple présence encourage les défections.', 			classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'INC', name:'Increvable', desc:'Même réduit en charpie, il bouge encore...', 			classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'SAN', name:'Sanguinaire', desc:'Adepte de la décoration extérieure.', 					classe:null, rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'PRE', name:'Précis', desc:'Une précision...divine !', 									classe:'ANG', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'BIE', name:'Bienveillant', desc:'Il aime son prochain.', 								classe:'ANG', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'DIS', name:'Discret', desc:'Ne fait pas un bruit.', 									classe:'ERM', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'VIF', name:'Vif', desc:'Difficile de le suivre.', 										classe:'ERM', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'COL', name:'Colossal', desc:'Est tombé une fois...de sommeil.', 						classe:'DEM', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'MOR', name:'Mortel', desc:'Un seul coup suffit.', 										classe:'DEM', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'IVB', name:'Invisible', desc:'Ce qu\'on ne voit pas n\'est pas inquiétant.', 			classe:'ASS', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'RUS', name:'Rusé', desc:'Trouve toujours une combine pour arriver à ses fins.', 		classe:'ASS', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'CAU', name:'Cauchemardesque', desc:'Instille la peur à sa simple évocation.', 			classe:'HOR', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'FOD', name:'Foudroyant', desc:'Frappe plus vite que son ombre.', 						classe:'HOR', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'IMP', name:'Imperturbable', desc:'Difficile de le distraire.', 							classe:'MOI', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'PRU', name:'Prudent', desc:'Se met en retrait pour mieux servir.', 						classe:'MOI', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'EME', name:'Emérite', desc:'Des années d\'entrainement.', 								classe:'CHE', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'MUS', name:'Musclé', desc:'Il faut pouvoir porter ces armures rutillantes.', 			classe:'CHE', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'INT', name:'Intelligent', desc:'Une grande soif de connaissances.', 					classe:'ENC', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'ERU', name:'Erudit', desc:'Erudit.', 													classe:'ENC', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'FUR', name:'Furtif', desc:'Sait se fondre dans le décor.', 								classe:'RAN', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'AST', name:'Astucieux', desc:'Connait mille tours.', 									classe:'RAN', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'CLA', name:'Clairvoyant', desc:'Voit tout, devine tout.', 								classe:'DRU', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'PRI', name:'Primitif', desc:'Robuste mais peu perspicace.', 							classe:'DRU', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'IVN', name:'Invulnérable', desc:'Une vraie force de la nature.', 						classe:'PRO', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'DES', name:'Destructeur', desc:'Une puissance phénoménale.', 							classe:'PRO', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'MIN', name:'Minutieux', desc:'S\'applique à ce que ses équipements soient parfaitement utilisables.', classe:'ART', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'PER', name:'Perfectionniste', desc:'Jamais pris en défaut.', 							classe:'ART', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'BAR', name:'Barbare', desc:'Une violence extrême.', 									classe:'BER', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'KAM', name:'Kamikaze', desc:'Le sacrifice de soi à l\'état pur.', 						classe:'BER', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'FOU', name:'Fou', desc:'Complètement imprévisible.', 									classe:'PYR', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'FRE', name:'Frèle', desc:'Une faible constitution peut s\'avérer être un avantage décisif.', classe:'PYR', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'MYS', name:'Mystérieux', desc:'Mais qui est-il ?.', 									classe:'ELE', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'IPL', name:'Implacable', desc:'Ira jusqu\'au bout de ses ressources.', 					classe:'ELE', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'VIR', name:'Virtuose', desc:'Un véritable spectacle.', 									classe:'DUE', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'MAR', name:'Maître d\'arme', desc:'Maîtrise tout type d\'arme.', 						classe:'DUE', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'DIS', name:'Distrait', desc:'Perdu dans ses pensées.', 									classe:'MAG', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'SAV', name:'Savant', desc:'Une bible de connaissances.', 								classe:'MAG', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'FER', name:'Féroce', desc:'Un danger permanent.', 										classe:'CHN', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'SAU', name:'Sauvage', desc:'Aucune notion de civilité.', 								classe:'CHN', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'IQR', name:'Inquisiteur', desc:'Rien ne lui échappe !.', 								classe:'LIC', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'IPY', name:'Impitoyable', desc:'Ne vous laisse aucunes chances.', 						classe:'LIC', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'PSP', name:'Perspicace', desc:'Visualise bien les dynamiques de groupes.', 				classe:'SOM', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 },
			{ code:'DSC', name:'Discipliné', desc:'Sait attendre le bon moment pour frapper.', 				classe:'SOM', rap:0 , per:0 , dex:0 , force:0 , res:0 , men:0 , foc:0 , mnc:0 , sur:0 , letal:0 }
		],
		skills : [
			{ code:'ATT', name:'Attaquer', desc:'Frapper son ennemi jusqu\'à ce qu\'il soit KO ou mort.', 	classe:null, vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'REP', name:'Se reposer', desc:'reprendre son souffle, pour repartir à l\'attaque.', 	classe:null, vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ANG', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ANG', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ANG', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ANG', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ERM', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ERM', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ERM', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ERM', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'DEM', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'DEM', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'DEM', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'DEM', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ASS', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ASS', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ASS', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ASS', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'HOR', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'HOR', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'HOR', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'HOR', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'MOI', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'MOI', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'MOI', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'MOI', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'CHE', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'CHE', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'CHE', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'CHE', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ENC', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ENC', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ENC', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ENC', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'RAN', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'RAN', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'RAN', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'RAN', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'DRU', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'DRU', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'DRU', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'DRU', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'PRO', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'PRO', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'PRO', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'PRO', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ART', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ART', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ART', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ART', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'BER', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'BER', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'BER', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'BER', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'PYR', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'PYR', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'PYR', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'PYR', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ELE', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ELE', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ELE', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'ELE', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'DUE', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'DUE', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'DUE', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'DUE', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'MAG', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'MAG', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'MAG', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'MAG', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'CHN', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'CHN', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'CHN', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'CHN', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'LIC', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'LIC', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'LIC', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'LIC', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'SOM', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'SOM', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'SOM', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 },
			{ code:'1', name:'1', desc:'1', classe:'SOM', vit:0, esq:0, tou:0, pui:0, vol:0, arm:0, vie:0, sou:0, mor:0, letal:0 }
		]
},
{
	name : '1.1',
	desc : 'pas de maj dans cette version.'
}];